project_id = "xbgxnwzluykgxcxujeay"

[functions.news-feed]
verify_jwt = false

[functions.transcribe-voice]
verify_jwt = true

[functions.admin-phone-login]
verify_jwt = false

[functions.send-monthly-account-summary]
verify_jwt = false
