ALTER TABLE public.news_publishers
  ADD COLUMN IF NOT EXISTS bio text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS age integer DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS experience text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fun_fact text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS slug text DEFAULT NULL;